name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  owasp-zap:
    name: OWASP ZAP Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: 'http://localhost:5000/'