name: StackHawk Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-stackhawk:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker-compose up -d
    - name: Run StackHawk Scan
      uses: stackhawk/hawk-github-action@v2
      with:
        apiKey: ${{ secrets.GITHUBKEY }}
        
